### ISSUE TITLE
Bot starts running slowly after several hundred responses

### ISSUE THREAD

**Issue by asya-bergal** [gunthercox/ChatterBot#42] opened 2015-05-27 03:46 UTC
On my computer the bot delays a few seconds between inputs when I train with with 1000 example lines. It gets worse the more training data there is. Is there any way to speed up the performance, or is this just the nature of the beast?

**Comment by gunthercox** [comment] 2015-05-27 21:09
If you install `python-cjson` ChatterBot's [default database module](https://github.com/gunthercox/jsondb) will detect it and use it instead of python's built in `json`. The [cjson module](https://pypi.python.org/pypi/python-cjson) has much better preformance and supposedly offers up to 250 times the speed when processing data.

Asside from this, as I briefly mentioned in https://github.com/gunthercox/ChatterBot/issues/41#issuecomment-106066687, there is the oppertunity to write storage adapters for other types of databases. ChatterBot's default storage system uses a json file. An adapter to use another type of database could easily be created. Let me know if you end up creating an adapter for another database type, pull requests are always welcome :smile:.

**Comment by brizzbane** [comment] 2015-06-04 00:55
Discovered this project after CleverBot's api (undocumented) went down.

I work daily with Elasticsearch, I think combined w/this (only have *just* started reviewing the code), it could probably be made to scale very well.  Haven't looked yet how the JSON fields correlate to responses (FYI elasticsearch is JSON)--but I imagine the features of elasticsearch'es SEARCH could be used to greatly improve the speed of responses.

**Comment by gunthercox** [comment] 2015-07-22 01:23
Closing this one off as it is a duplicate of https://github.com/gunthercox/ChatterBot/issues/45

**Closed by gunthercox** 2015-07-22 01:23 UTC

**Comment by phpmind** [comment] 2016-11-18 18:31
brizzbane - Did u create Elasticsearch  +ChatterBot adapter ?
