### ISSUE TITLE
Error for running example

### ISSUE THREAD

**Issue by Niccolohui** [gunthercox/ChatterBot#448] opened 2016-12-01 10:06 UTC
Hi all,

I got error for running this example

```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
import logging


# Uncomment the following line to enable verbose logging
# logging.basicConfig(level=logging.INFO)

# Create a new instance of a ChatBot
bot = ChatBot("Terminal",
    storage_adapter="chatterbot.storage.JsonFileStorageAdapter",
    logic_adapters=[
        "chatterbot.logic.MathematicalEvaluation",
        "chatterbot.logic.TimeLogicAdapter",
        "chatterbot.logic.ClosestMatchAdapter"
    ],
    input_adapter="chatterbot.input.TerminalAdapter",
    output_adapter="chatterbot.output.TerminalAdapter",
    database="../database.db"
)

print("Type something to begin...")

# The following loop will execute each time the user enters input
while True:
    try:
        # We pass None to this method because the parameter
        # is not used by the TerminalAdapter
        bot_input = bot.get_response(None)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break

```
```
> Traceback (most recent call last):
  File "chatbot.py", line 19, in <module>
    database="../database.db"
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 37, in __init__
    self.validate_adapter_class(storage_adapter, StorageAdapter)
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 151, in validate_adapter_class
    if not issubclass(import_module(validate_class), Adapter):
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/utils/module_loading.py", line 12, in import_module
    module = importlib.import_module(module_path)
  File "/Users/niccolo/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'chatterbot.storage'
```

anyone can help?

**Comment by vkosuri** [comment] 2016-12-01 11:30
@Niccolohui which version of chatterbot are you using? Try

```Shell
pip install --upgrade chatterbot
```

**Comment by nimraTassawar** [comment] 2016-12-01 12:30
@Niccolohui 
i think you are not using updated chatterbot. 
e.g., your storage_adapter="chatterbot.storage.JsonFileStorageAdapter", should be replaced to     storage_adapter="chatterbot.adapters.storage.JsonFileStorageAdapter",

**Comment by Niccolohui** [comment] 2016-12-01 15:20
@vkosuri Thanks but i have updated the chatterbot again. and i got this

> Traceback (most recent call last):
  File "chatbot.py", line 2, in <module>
    from chatterbot import ChatBot
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 4, in <module>
    from .logic import MultiLogicAdapter
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/logic/__init__.py", line 1, in <module>
    from .logic_adapter import LogicAdapter
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/logic/logic_adapter.py", line 3, in <module>
    from chatterbot.utils import import_module
ImportError: cannot import name 'import_module'

**Comment by gunthercox** [comment] 2016-12-01 15:25
See https://github.com/gunthercox/ChatterBot/issues/443#issuecomment-264070500

**Comment by Niccolohui** [comment] 2016-12-01 15:51
@gunthercox  thanks!!
I have removed the directory named utils and adapters and i got this.

>   File "chatbot.py", line 19, in <module>
    database="../database.db"
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 31, in __init__
    utils.validate_adapter_class(storage_adapter, StorageAdapter)
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/utils.py", line 112, in validate_adapter_class
    if not issubclass(import_module(validate_class), Adapter):
  File "/Users/niccolo/anaconda/lib/python3.5/site-packages/chatterbot/utils.py", line 63, in import_module
    module = importlib.import_module(module_path)
  File "/Users/niccolo/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'chatterbot.adapters.storage'; 'chatterbot.adapters' is not a package

**Comment by gunthercox** [comment] 2016-12-01 15:53
If you also changed the example file as @nimraTassawar described, undo those changes.

**Comment by gunthercox** [comment] 2016-12-02 13:48
This issue is a duplicate of https://github.com/gunthercox/ChatterBot/issues/443
Please direct any further questions to that ticket.

**Closed by gunthercox** 2016-12-02 13:48 UTC
