### ISSUE TITLE
Does it support flow based dialog conversation?

### ISSUE THREAD

**Issue by kenyeung128** [gunthercox/ChatterBot#728] opened 2017-05-11 09:07 UTC
Does it support flow based dialog conversation?

**Comment by gunthercox** [comment] 2017-05-11 11:20
Hi @kenyeung128, could you describe what you mean by a "flow based" conversation? If you could provided an example or link to an article that describes it that would be perfect.

**Comment by Cosmos19** [comment] 2017-05-12 11:46
Am also facing the same problem.  if am right.

Lets take below scenario.

JSON:
[
"right",
"okay"
],
[
"i have problem with eye",
"which side",
"right",
"oh...thats bad. What happened to right eye.?"
]

conversation:
Me: I have problem with eye.
bot: which side
Me: right
Bot: Okay

In the above scenario. if am replying with "right" means I want the bot to reply "oh...thats bad. What happened to right eye.?". but instead of that it will reply "okay". because of the best match.

@kenyeung128 Please correct me if am wrong.

@gunthercox  Am facing this situation. :(

Thanks in advance.!

**Comment by gunthercox** [comment] 2017-07-04 13:32
I'm closing this ticket as a duplicate of #276. Feel free to click the subscribe button on that page to follow the progress for when it is resolved.

**Closed by gunthercox** 2017-07-04 13:32 UTC
Labels: question
