### ISSUE TITLE
How to use mongodb as the backend for chatterbot

### ISSUE THREAD

**Issue by SharkBaby** [gunthercox/ChatterBot#1025] opened 2017-10-13 06:32 UTC
Hi Team, 

I have tried to use pymongo3.5.1 or  mongoengine0.9.0, but I always got below issue after I change the code in settings.py
``` Python
DATABASES = { 
     'default': {
          'ENGINE': 'django.db.backends.dummy',
     }
}
```
I have searched for some solutions , but it still donot work, and I always got below error.
``` Bash
  File "C:\Programs\Python\Python36\lib\site-packages\chatterbot\input\input_adapter.py", line 24, in process_input_statement                                            
    existing_statement = self.chatbot.storage.find(input_statement.text)                                                                                                 
  File "C:\Programs\Python\Python36\lib\site-packages\chatterbot\storage\django_storage.py", line 25, in find                                                            
    return Statement.objects.get(text=statement_text)                                                                                                                    
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 85, in manager_method                                                           
    return getattr(self.get_queryset(), name)(*args, **kwargs)                                                                                                           
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 374, in get                                                                       
    num = len(clone)                                                                                                                                                     
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 232, in __len__                                                                   
    self._fetch_all()                                                                                                                                                    
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all                                                               
    self._result_cache = list(self._iterable_class(self))                                                                                                                
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 53, in __iter__                                                                   
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)                                                                                                     
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 871, in execute_sql                                                        
    sql, params = self.as_sql()                                                                                                                                          
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 423, in as_sql                                                             
    extra_select, order_by, group_by = self.pre_sql_setup()                                                                                                              
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 46, in pre_sql_setup                                                       
    self.setup_query()                                                                                                                                                   
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 37, in setup_query                                                         
    self.select, self.klass_info, self.annotation_col_map = self.get_select()                                                                                            
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 227, in get_select                                                         
    sql, params = self.compile(col, select_format=True)                                                                                                                  
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 373, in compile                                                            
    sql, params = node.as_sql(self, self.connection)                                                                                                                     
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\expressions.py", line 695, in as_sql                                                              
    return "%s.%s" % (qn(self.alias), qn(self.target.column)), []                                                                                                        
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 364, in quote_name_unless_alias                                            
    r = self.connection.ops.quote_name(name)                                                                                                                             
  File "C:\Programs\Python\Python36\lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain                                                            
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "                                                                                           
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```

Can some one who could tell us how we can use mongodb as the backend for chatterbot , thanks so much.

**Comment by vkosuri** [comment] 2017-10-13 17:37
> ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

@SharkBaby The message it self suggesting you DB is improperly configured, please try to use a valid DB configuration which is working on your machine.

After configuration still it fails, post your stack trace, we will try to help you.

**Comment by SharkBaby** [comment] 2017-10-16 03:35
@vkosuri , you can below the settings for the mongodb in mongo.py file
![image](https://user-images.githubusercontent.com/18545909/31594155-e21c7dc8-b265-11e7-8831-b8c93c609952.png)
self.database_name = self.kwargs.get(
            'database', 'chatterbot-database'
        )
        self.database_uri = self.kwargs.get(
            'database_uri', 'mongodb://localhost:27017/'
        )
and I create chatterbot-database in my mongodb, you can check below
![image](https://user-images.githubusercontent.com/18545909/31594186-0f12b040-b266-11e7-89ca-0d03e32cea42.png)
>show dbs
chatterbot-database 0.000GB

I just wonder know how to configure the settings.py file when I use mongodb as the backend. thanks so much.

**Comment by gunthercox** [comment] 2017-12-03 01:43
Duplicate of #1011

**Closed by gunthercox** 2017-12-03 01:43 UTC
