### ISSUE TITLE
Training bots seperately.

### ISSUE THREAD

**Issue by CallumHemsley** [gunthercox/ChatterBot#1371] opened 2018-08-14 08:16 UTC
Is there any way to have, say two bots, one for English and one for Chinese, that are can be trained separately? 
This would improve response time I believe. One solution I can see is creating two databases for each bot so they don't overlap. I'm curious if there is a better way in which I can use only the one database?
For example, is there some way to split the tables WITHIN the SAME database, so that each bot only searches from it's own tables?

**Comment by vkosuri** [comment] 2018-08-14 14:46
I think this feature not yet implemented or not supported by framework.

**Comment by CallumHemsley** [comment] 2018-08-14 14:59
@vkosuri I see, thanks.

**Comment by gunthercox** [comment] 2018-09-29 12:10
I'm going to close this off as a duplicate of #1232. Feel free to subscribe to that issue for updates. I'm labeling this functionality as a feature and I'd like to introduce it to ChatterBot in the future.

**Closed by gunthercox** 2018-09-29 12:10 UTC
Labels: feature
