### ISSUE TITLE
Support for session_id in logic adapters so message contexts can be maintained

### ISSUE THREAD

**Issue by lucaszanella** [gunthercox/ChatterBot#605] opened 2017-01-24 23:49 UTC
As I see, in `get_response()` we have this line:

`statement, response = self.generate_response(input_statement, session_id)`

and `generate_response()` does the following:

```
self.storage.generate_base_query(self, session_id)

# Select a response to the input statement
response = self.logic.process(input_statement)

return input_statement, response
```

as I see, the logic adapters aren't able to work with sessions. That is, they can't consult previous messages to learn the **context** of the chat (although the bot learns answers from previous ones). 

Wouldn't it be nice to pass `session_id` for logic adapters so they could maintain a context for the message?  This way we could implement **stories**, just like [wit.ai](https://wit.ai), not just static replies based on what the bot learned somewhere.

**Comment by gunthercox** [comment] 2017-01-25 01:30
@lucaszanella I agree, I would be happy to make changes to allow this.

**Comment by gunthercox** [comment] 2017-01-25 02:09
I'm actually in the process of making some rather large changes that will make this much easier to do. Each statement will end up having a reference to the session that it is a part of.

**Comment by lucaszanella** [comment] 2017-01-25 02:34
Nice! Context is good for bots, it'll be crucial to have sessions in order
to implement stories. Imagine a bot for a store: it first needs to get
information about the client, which is a story. Then, it needs to chat with
the client to pick the product he wants to buy, that's another story.
Stories can start other stores, just like wit.ai does.

Your project is the most modern one (that's still offline) I've found while
searching for bots, and I like it being in python: easy and good for
computations.

I'm thinking in writing a logic adapter which breaks up a phrase in a list
of words, searches in a dictionary of the most common words in the
language, and then pick the most uncommon words. This would be great for
phrases like this:

"I want to order a pizza"

'pizza' would be the most uncommon word. Associated with the verb 'order',
you know that the client wants to order a pizza. What you think?

Again, nice work, definitely using it in my project!

**Comment by vkosuri** [comment] 2017-01-25 02:47
I think this could you help you [Analyzing Sentence Structure](http://www.nltk.org/book/ch08.html)

**Comment by lucaszanella** [comment] 2017-01-25 03:00
Did you implement these things in chatterbot yet?

Em 25 de jan de 2017 00:47, "Mallikarjunarao Kosuri" <
notifications@github.com> escreveu:

**Comment by vkosuri** [comment] 2017-01-25 05:34
No i am learning these techniques

**Comment by lucaszanella** [comment] 2017-01-25 18:10
Do you have a date to release it? I was thinking about implementing myself
but it's better to wait for your implementation

Em 24 de jan de 2017 23:30, "Gunther Cox" <notifications@github.com>
escreveu:

**Comment by gunthercox** [comment] 2017-01-25 23:18
@lucaszanella I don't have a date set yet for releasing the changes that will associate statements with specific chat sessions. Right now I'd estimate that the release is about a month away. The reason for this is that it is a part of a much larger change that is intended to make it easier to search through past conversations to find ones that were similar to the current conversation. As a side effect each statement will have a reference to the conversation (session) that it was a part of.

I'm planning on creating a "development" branch which will contain the latest changes before the official release.

**Comment by 360d-io-labs** [comment] 2017-03-02 11:16
Hi is there any news regarding this? I checked the dev branch but it has not been updated for a while? Is there something we can do to help?

**Comment by gunthercox** [comment] 2017-03-04 15:08
Hi @360d-io-labs, I appreciate the offer. The development branch currently contains some major changes and improvements but I am currently getting random test failures. I haven't had a chance to pinpoint the exact cause. Examples of these failures can be viewed in the Travis CI output https://travis-ci.org/gunthercox/ChatterBot/builds/196184505

**Comment by saurabhzuve** [comment] 2017-08-18 08:53
Hey in order to maintain context I was trying to build a Logical Adapter for each context that I want in my conversation. But the problem is that I need the last statements that were made in the conversation in the Logical Adapter such that I can define the rules to be followed if a particular set of statements have already been passed.
I am unable to get the last mentioned response or input statement in my Logical Adapter. I know that I can get these by the following commands:
bot.conversation_sessions.get(self.bot.default_session.uuid).conversation.get_last_response_statement().text
but this is not working inside the Logical Adapter
It says bot not defined.

Please help! How can I get through this? I am new to python.

**Comment by gunthercox** [comment] 2017-08-20 14:05
@saurabhzuve I think you need `self.chatbot` insted of `self.bot`

**Comment by gunthercox** [comment] 2018-09-15 21:05
This has been completed, sort of. ChatterBot no longer has sessions, those have been replaced with "conversations". `conversation` is a string attribute on statements that can be used to indicate the conversation that the statement was a part of.

I'm going to close this ticket off for now, feel free to open a new one if any questions related to conversations come up.

**Closed by gunthercox** 2018-09-15 21:05 UTC
Labels: enhancement
