### ISSUE TITLE
Tell Chatterbot if it is the correct answer

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#935] opened 2017-08-15 05:38 UTC
Another future request for you. 
I think this is maybe already possible to do. But it should be nice if you can add a Voting function to the answer from the chatterbot.

That mean for every time you ask and get a responds you can vote to add another 👍 +1 or 👎 : (-2) to the counter.
In that case we can easier train our chatterbot for the correct answer.
If we hit 👎 the chatterbot will automatic do another responds and we can then vote again until the correct answer comes up.

If we hit the 👎 let say 5 times, we should switch to manual mode where Person-To-Person communication comes in. And Chatterbot will only read the Statement (User) + Responds (Admin) = insert to data for each line they type in to the database to be able to understand even more.

**Comment by nggary** [comment] 2017-08-23 06:05
`# -*- coding: utf-8 -*-

from chatterbot import ChatBot

bot = ChatBot(
    'Feedback Learning Bot',
    storage_adapter='chatterbot.storage.JsonFileStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch'
    ],
    input_adapter='chatterbot.input.TerminalAdapter',
 output_adapter='chatterbot.output.TerminalAdapter')

DEFAULT_SESSION_ID = bot.default_session.id

def get_feedback():
    from chatterbot.utils import input_function
    text = input_function()
    if 'Yes' in text:
        return True
    elif 'No' in text:
        return False
    else:
        print('Please type either "Yes" or "No"')
        return get_feedback()

print('Type something to begin...')


while True:
    try:
        input_statement = bot.input.process_input_statement()
        statement, response = bot.generate_response(input_statement, DEFAULT_SESSION_ID)
        print('\n Is "{}" this a coherent response to "{}"? \n'.format(response, input_statement))
        if get_feedback():
            bot.learn_response(response,input_statement)
        bot.output.process_response(response)

        bot.conversation_sessions.update(
            bot.default_session.id_string,
            (statement, response, )
        )

    except (KeyboardInterrupt, EOFError, SystemExit):
        break`

**Comment by nggary** [comment] 2017-08-23 06:06
Above is the sample of let user determine is it the correct response by using terminal mode

**Comment by gunthercox** [comment] 2017-10-10 09:54
I'm going to close this off as a duplicate of #476. @Issen007 Feel free to let me know if you believe there is any components of this that occur outside the scope of feedback learning.

**Closed by gunthercox** 2017-10-10 09:54 UTC
