### ISSUE TITLE
chatbot error

### ISSUE THREAD

**Issue by Aniket573** [gunthercox/ChatterBot#2020] opened 2020-08-13 12:59 UTC
Getting error on running the below code in pydev in eclipse:

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot('Charlie')
trainer = ListTrainer(chatbot)

trainer.train([
"Hi, can I help you?",
"Sure, I'd like to book a flight to Iceland.",
"Your flight has been booked."
])

response = chatbot.get_response('I would like to book a flight.')
print(response)

Error:

Traceback (most recent call last):
  File "D:\Users\ABiswa14\eclipse-workspace\PyDev\src\chatbot.py", line 4, in <module>
    chatbot = ChatBot('Charlie')
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\chatterbot.py", line 34, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\storage\sql_storage.py", line 22, in __init__
    from sqlalchemy import create_engine
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 264, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by gunthercox** [comment] 2020-08-19 11:07
A number of people have posted about this error. This is because of a comparability issue in `sqlalchemy` when running in Python 3.8.

https://github.com/sqlalchemy/sqlalchemy/issues/4731

I think this issue might already be fixed on the `1.0` branch, but I have to do a release to PyPi before it will be available.

**Comment by gunthercox** [comment] 2020-08-20 10:51
Duplicate of #1941

**Closed by gunthercox** 2020-08-20 10:51 UTC
Labels: answered
