### ISSUE TITLE
Transfer database from JSON to MongoDB

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [gunthercox/ChatterBot#95] opened 2015-12-08 20:41 UTC
I have a JSON database with 1000+ responses, and even after installing `python-cjson` it's still pretty slow. From what I understand, MongoDB is much faster. Is this correct, and is there an easy way to switch between the two

**Comment by LucasZielke** [comment] 2015-12-09 02:37
If i was reading correctly you should just be able to insert the raw json file into mongo db and it seems to be structured pretty simmilarly but you should probably try to restructure your json file to follow the same format as @gunthercox 's files are before, so that we can code the bot to grab the info from the db the same way it grabs from local

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-09 12:05
So, if I have my local database, how programmatically do I "insert the file into mongo DB"?

**Comment by LucasZielke** [comment] 2015-12-09 19:03
Try this 
```
from pymongo import MongoClient
import json

HOST,PORT = ('localhost','27017')
DATABASE_NAME = 'test-database'
COLLECTION_NAME = 'test-collection'

client = MongoClient(HOST,PORT) #Connect to Mongo db

db = client[DATABASE_NAME] #Connect to specific database
collection = db[COLLECTION_NAME] #Access specific collection

#Then you would need to load a json into a dict(post) then post it using

posts = db.posts
post_id = posts.insert_one(post).inserted_id
```

**Comment by LucasZielke** [comment] 2015-12-09 20:33
Think of a MongoDb as a json file structured like
```
"Database":[  
   {  
      "Collection":[  
         {  
            "Document":[  
               {  
                  "data":"data",
                  "moreData":"data"
               },
               {  
                  "data":"data2",
                  "moreData":"data2"
               },

            ],

         },
         {  
            "Document2":[  
               {  
                  "data":"data3",
                  "moreData":"data3"
               },
               {  
                  "data":"data4",
                  "moreData":"data4"
               },

            ],

         },

      ],

   },

]
```

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-09 22:01
So, if I understand correctly, mongoDB is web based? What makes it faster than JSON? Also, if it's not too bothersome, how can I put the JSON into a dict? Should I use [json_util](http://api.mongodb.org/python/current/api/bson/json_util.html) from MongoDB?

**Comment by LucasZielke** [comment] 2015-12-09 22:52
Ive never used the json_util but if im correct
```
import json
f = open(filename, 'r')
jsonData = json.loads(f.read())
```
jsonData should be a dict

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-09 22:55
OK, great. I'll look into this

**Comment by LucasZielke** [comment] 2015-12-09 23:01
Ok, push it into your fork of the project and mention me, i want to see what youre doing  with it, and the json file

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-10 00:49
Ok. I'm actually not planing to integrate this into my fork, but instead into my personal bot which is slowing down. My fork will likely just include changes to the actual library, this is code I'd like to run once to make a change. My fork will likely just be support for dynamic responses through functions, which I'd like to implement into `train` rather than as a plugin.

**Comment by LucasZielke** [comment] 2015-12-10 06:27
Might i suggest implementing both, as i was saying prior, have inline parsing for the bots output and train it with code inside [ ] 's

https://github.com/gunthercox/ChatterBot/issues/94#issuecomment-162667398

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-10 11:50
I'll see, I'm really just modifying for one personal project. I'll see how it goes.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-11 00:45
It seems like kind of a limitation that under MongoDB, keys cannot contain the `.` character

**Comment by LucasZielke** [comment] 2015-12-11 02:43
What would the reason you would put a `.` in your db??

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-11 02:56
Some responses have multiple sentences and therefore periosd

**Comment by gunthercox** [comment] 2015-12-12 13:17
Hi guys, sorry for the late response. If you are still looking to migrate from jsondb to mongo then I believe the following code snippet should help quite a bit.

```python
from chatterbot.adapters.storage import MongoDatabaseAdapter
from chatterbot.adapters.storage import JsonDatabaseAdapter

mongo_adapter = MongoDatabaseAdapter(database=my_mongo_database_name)
json_adapter = JsonDatabaseAdapter(database=my_json_database_name)

# Loop through every statement that exists in the json database
for statement in json_adapter.filter():

    # Add the statement to the mongo database
    mongo_adapter.update(statement)
```

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-12 17:09
That looks great. I was previously unsuccessful, I tried making my own database, and naming the collection 'statements' as in the code for the storage adapter. I'll try this and we will see how much faster Mongo is than JSON

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-12 21:17
@gunthercox Although MongoDB makes response time at least 3 times faster, it appears everything has been mixed up in transferring. An example conversation with the newly trained mongo bot:
>Me: Hello
Bot: Yes I am
Me: What's up?
Bot: 1963
Me: Hello
Bot: Or is it?
Me: What's your name
Bot: How old are you?

Having a similar conversation with the old JSON bot:
>Me: hello
Bot: FROM THE OTHER SIDE
-Adele
Me: What's up?
Bot: Not much.
Me: That's cool
Bot: No its not. We need more gun control don't vote for trump

(These are the intended responses even if they seem strange)

My best guess (from the fact that `len(json_adapter) == len(json.loads(open("database.db","r").read()).keys())`) is that your solution is only loading the keys into the Mongo Database, each as a response to the previous.

**Comment by gunthercox** [comment] 2015-12-13 15:40
I will look into this. This may indicate an issue with the mongodb adapter.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-13 15:50
I also have had some issues training it with the text of shakespeare's Julius Caesar, but assumed that was an error on my part... I'll check whether I get the intended behavior with a JSON database, which would indicate an issue with the MongoDB adapter.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-13 16:25
It appears that the MongoDB adapter does have some issues. Training with the text of Julius Caesar, under the JSON database I get:
>
**Me:** Peace, Ho! Let us hear him!
**Bot:** Friends, Romans, countrymen, lend me your ears;
I come to bury Caesar, not to praise him.
The evil that men do lives after them;
The good is oft interred with their bones;
So let it be with Caesar. The noble Brutus
Hath told you Caesar was ambitious:
If it were so, it was a grievous fault,
And grievously hath Caesar answer'd it.
Here, under leave of Brutus and the rest--
For Brutus is an honourable man;
So are they all, all honourable men--
Come I to speak in Caesar's funeral.
He was my friend, faithful and just to me:
But Brutus says he was ambitious;
And Brutus is an honourable man.
He hath brought many captives home to Rome
Whose ransoms did the general coffers fill:
Did this in Caesar seem ambitious?
When that the poor have cried, Caesar hath wept:
Ambition should be made of sterner stuff:
Yet Brutus says he was ambitious;
And Brutus is an honourable man.
You all did see that on the Lupercal
I thrice presented him a kingly crown,
Which he did thrice refuse: was this ambition?
Yet Brutus says he was ambitious;
And, sure, he is an honourable man.
I speak not to disprove what Brutus spoke,
But here I am to speak what I do know.
You all did love him once, not without cause:
What cause withholds you then, to mourn for him?
O judgment! thou art fled to brutish beasts,
And men have lost their reason. Bear with me;
My heart is in the coffin there with Caesar,
And I must pause till it come back to me.
**Me: **Methinks there is much reason in his sayings. 
**Bot: **If thou consider rightly of the matter,
Caesar has had great wrong.


But with a MongoDB adapter:
>
**Me: **Peace, ho! Let us hear him!
**Bot: ** Caesar, 'tis strucken eight.
**Me: ** Methinks there is much reason in his sayings.
**Bot: ** There is some grudge between 'em, 'tis not meet
They be alone.

**Comment by gunthercox** [comment] 2015-12-13 21:27
I believe I have tracked down the issue. Response objects on each statement were being returned as a dictionary instead of a normalized list of objects when the filter method was being called. https://github.com/gunthercox/ChatterBot/pull/96 should correct the problem. I will merge it as soon as tests pass.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 00:59
Great! I look forward to being able to use faster databases reliably!

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 01:58
Issue appears to be fixed, and MongoDB shows ¼ the response time, yay! Thanks for your help, all.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 02:10
Not quite, appears you forgot to convert to dict in line 41 of `jsondatabase.py`. I think it's likely you left `response` as a list when you meant to change it to a dict. You call `text = response["text"]` on line 41, which raises an error, because `response` is a list, not a dict and cannot be indexed by a string. Either you meant `text = response[text]` where text is an integer, or you meant for `response` to be a dict. 

BTW I am getting this error running the transfer code you have included above, I don't know if normal usage is affected by this.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 12:24
This means that conversation with JSON database is broken completely... I cannot have a conversation with my bot from before the update.

**Comment by gunthercox** [comment] 2015-12-14 17:49
@The-Penultimate-Defenestrator I'm not seeing this error on my end, and the code appears correct.

To explain what is being done circa line 41:
```python
                                            # The response list is a list of dictionaries in which each dict is a response
        for response in response_list:      # For each response that the current statement is in response to
            text = response["text"]         # Save the text value of the response
            del(response["text"])           # remove the text key from the dictionary

                                            # Append the normalized Response object to the Statement's response list
            in_response_to.append(
                Response(text, **response)
            )
```

Can you post the stack trace you are getting?

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 18:22
Yes, my stack looks like:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 187, in train
    self.trainer.train_from_corpora(corpora)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/training.py", line 37, in train_from_corpora
    self.train_from_list(pair)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/training.py", line 16, in train_from_list
    statement = self.storage.find(text)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/storage/jsondatabase.py", line 28, in find
    response_list = self.deserialize_responses(values["in_response_to"])
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/storage/jsondatabase.py", line 41, in deserialize_responses
    text = response["text"]
TypeError: list indices must be integers, not str
```

**Comment by gunthercox** [comment] 2015-12-14 19:43
I apologize, I'm fairly certain I just figured out what the issue is. There was a schema change in the json database format the also got released in 0.3.2. (https://github.com/gunthercox/ChatterBot/pull/84). The change improves response object representations to make them more flexible, however it breaks backwards compatibility.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 19:52
"breaks backwards compatibility" does this mean I cannot use a previous database with the new format? If it only breaks backwards compatibility, why is an error thrown on the simple usage I included above:

```
import chatterbot
c = chatterbot.ChatBot("Test_Bot")
c.get_response("hello")
```

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-14 20:27
Ok, if I remove the existing database and run the code again, the error disappears. How can I move my database from one format to another? The only way I can possibly think of is to have multiple virtual environments with different versions of the library in them, then somehow output from one into a different format which I import into the other. I'm not smart enough to figure this out, do you have a solution?

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-15 01:32
My approach to transferring the database has failed. My planned approach:

1. Revert to chatterbot 0.3.0
2. Read JSON database and convert to MongoDB
3. Go back to 0.3.2
4. Read MongoDB database and convert back to JSON

I was hoping that only reading of the mongo database had been broken, not writing. I now cannot call `filter()` in 0.3.0 either without throwing an error, after about 8 seconds I get 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "usr/local/lib/python2.7/dist-packages/chatterbot/adapters/storage/jsondatabase.py", line 41, in _objectify_response_list
    text = item[0]
KeyError:0
```

So, it looks like 0.3.2 actually modified my database before deciding it couldn't read it? It looks like it is trying to desperately read a list that has been converted to a dict. I believe I was running 0.3.0 before, then after upgrading and re-downgrading my database is broken.

**Comment by gunthercox** [comment] 2015-12-15 02:07
Not sure if there is simple a solution now that the database has both types of data structures within it.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-15 02:10
Ok. I'm fine with losing all data with the new type of data structure, as
it represents very little data. Is there a way to remove that and then
convert all other data?

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-15 02:10
I'm fine with losing all the data represented by the new type of data structure, might this allow for a simpler solution?

**Comment by gunthercox** [comment] 2015-12-15 02:29
Possibly. This script may help. This should remove any invalid response keys that were created by the new version, assuming it can load a statement. I recommend saving a backup first.

```python
from chatterbot.conversation import Statement
from chatterbot.adapters.storage import JsonDatabaseAdapter

adapter = JsonDatabaseAdapter(.....)

# Step 1: Remove invalid response data from statements (there should be very few of these)
for key in adapter._keys():
	try:
		statement = adapter.find(key)
	except:
		adapter.update(Statement(key))
```

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-15 02:31
Thanks, I'll definitely try this

**Comment by gunthercox** [comment] 2015-12-15 02:33
From there, if you want to migrate the database to the new version, it might be best to attempt to export it as a corpus format. See https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/corpus/data/english/conversations.json

Then it would be possible to import it into the new database schema and retain all of the existing structure.

I don't have a script for this yet, but it would not be difficult to create.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-15 02:34
Great. I'll try this. Probably going to sleep in 20-ish minutes as I have school tomorrow, I'll report back when I have a result.

**Comment by The-Penultimate-Defenestrator** [comment] 2015-12-16 16:41
I'm not exactly sure how to export to a corpus format, I can iterate through `JsonDatabaseAdapter.filter()` to find all responses but I'm not sure how to separate them into separate conversations.

**Comment by gunthercox** [comment] 2016-01-26 13:13
@The-Penultimate-Defenestrator Were you ever able to resolve your issue?

**Comment by gunthercox** [comment] 2016-02-04 02:00
Hi, @The-Penultimate-Defenestrator I am going to close this issue, please re-open if you need further assistance.

**Closed by gunthercox** 2016-02-04 02:00 UTC

**Comment by The-Penultimate-Defenestrator** [comment] 2016-02-04 02:30
No, it's fine, I've started a new database with the new format. No worries.
