### ISSUE TITLE
response cannot be updated

### ISSUE THREAD

**Issue by jaysharp** [gunthercox/ChatterBot#974] opened 2017-09-06 11:28 UTC
when realizing there is typo in response or just wrong input, retrain also can't update the very response.

**Comment by vkosuri** [comment] 2017-09-06 18:09
The retraining will check for existing statement, if any existing statement are found it will update occurrence count not the statement. 

Correct you corpus and delete existing database ``db.sqlite3`` and retrain you bot. Hope this will solve your problem.

Any comments or suggestions on training process?

**Comment by jaysharp** [comment] 2017-09-07 01:44
In the case that there is typo in response or such small mistakes, it seems inefficiently to delete and  retrain the whole bot. What if checking and replacing the old statement while training the bot?

**Comment by Issen007** [comment] 2017-09-12 13:11
@jaysharp are you using together it together with Django? In that case you can modify the line in the Django Admin.

**Comment by jaysharp** [comment] 2017-09-19 09:28
@Issen007 ：thank you. I don't use it together with Django

**Comment by Issen007** [comment] 2017-09-19 14:59
@jaysharp in that case open the Database UI/CLi and either modify that line or delete that row in the database.

**Comment by gunthercox** [comment] 2017-12-03 14:21
@jaysharp I'm going to consider adding a programmatic method for editing statements that a chat bot has learned.

In the mean time, I'm going to close this off and mark it as a duplicate of #696

**Closed by gunthercox** 2017-12-03 14:21 UTC
