### ISSUE TITLE
Implementing a retrieval-based model using tensorflow ?

### ISSUE THREAD

**Issue by phpmind** [gunthercox/ChatterBot#563] opened 2017-01-10 01:47 UTC
Hi,
How hard will it be to Implement retrieval-based model using Tensorflow as part of this project ?
I want to use seq2seq model as a part of this improvement. 
Thanks

**Comment by gunthercox** [comment] 2017-01-10 01:55
Hi, this likely wouldn't be too difficult. I would estimate a difficulty of maybe 2 out of 5 with 5 being the hardest to implement.

:star: :star:

**Comment by vkosuri** [comment] 2017-01-10 05:11
Some useful links, If you haven't seen before
https://keras.io/
https://github.com/farizrahman4u/seq2seq

**Comment by vkosuri** [comment] 2017-01-11 02:24
@gunthercox could you please let me know, what are advantages and disadvantages using seq2seq model in chatterbot

**Comment by phpmind** [comment] 2017-01-11 02:39
Some reference - 
http://www.wildml.com/2016/07/deep-learning-for-chatbots-2-retrieval-based-model-tensorflow/ 
https://github.com/dennybritz/chatbot-retrieval/

**Comment by vikramsoni2** [comment] 2018-02-02 14:27
hi @phpmind I am also looking to develop similar logic adapter, have you had any advancement on this topic? The model is easy to implement, I am concerned about how to integrate it with chatterbot storage. Because the data for NN wouldn't necessarily have the same structure

**Comment by khushbumodi0** [comment] 2018-11-20 09:00
hi, @gunthercox @vkosuri I am also looking to implement Tensorflow in chatterbot. Do you have any idea that how can I implement Tensorflow in Chatterbot?

**Comment by gunthercox** [comment] 2018-11-21 12:40
Hi @khushbumodi0, I have only looked into Tensorflow implementations briefly. I don't have anything that could demonstrate this effectively at the moment.

**Comment by gunthercox** [comment] 2019-01-17 01:53
Hi everyone, it's been a while but I'm actually going to close this ticket off as a duplicate of #761. I know this one is the older of the two but #761 has received a greater amount of comments and discussion. Let's redirect any future thoughts related to this subject to that ticket.

**Closed by gunthercox** 2019-01-17 01:53 UTC
