### ISSUE TITLE
'Chatbot' is not defined in Chatterbot and few more questions

### ISSUE THREAD

**Issue by herboratory** [gunthercox/ChatterBot#1542] opened 2018-12-30 14:29 UTC
I am making a chatbot through Chatterbot. I am facing the problems as follow:

1. when I run the code, it shows error, but the ChatBot is imported from chatterbot at the beginning?

> File ".../SquirralBot.py", line 5, in class SquirralBot: File "...SquirralBot.py", line 6, in SquirralBot bot = Chatbot("SquirralBot", NameError: name 'Chatbot' is not defined

2. I want to make the chatbot to distinguish specific texts then to trigger specific corpus, how can I make it? Is the "chatterbot.conversation.Response(text, **kwargs)" class for this purpose? e.g. when the user types "I am leaving", then it will trigger to call the training set "chatterbot.corpus.chinese.squirral_bye_conversation"?

3. Is it possible if I can store the reply specifically to the database e.g. MongoDB for different users? e.g. when user A replies "I am sick. I got fever and running nose", then the system store "sick" into "status" and "fever" and "running nose" into "symptoms" in the user A's data so that inside the database it would be like JSON:

```
{
     "user A", 
     "gender": "male", 
     "record": 
  [ 
        {
             "date": "25-12-2018", 
             "status": "fine", 
             "symptoms": "", 
        }, 
        { 
            "date": "26-12-2018", 
            "status": "sick", 
            "symptoms": "fever", "running nose"
        } 
}
```

4. Is it possible to make the chatbot can text the user in specific time range?

The code for the above mentioned is as following. I am very new in programming so the code may be a bit messy. Please feel free to correct. Many thanks.

```
import sys 
from chatterbot import ChatBot 
from chatterbot.trainers import ChatterBotCorpusTrainer

class SquirralBot:
    chatbot = Chatbot("SquirralBot",
    logic_adapters=[
        {
            "import_path": "chatterbot.logic.BestMatch",
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
            "response_selection_method": "chatterbot.response_selection.get_first_response"
        }
    ],storage_adapter = "chatterbot.storage.JsonFileStorageAdapter",database = "./SquirralBot_DB.json")

    def __init__(self):
        self.chatbot.set_trainer(ChatterBotCorpusTrainer)
        self.chatbot.train("chatterbot.corpus.chinese.squirral_greeting", "chatterbot.corpus.chinese.squirral_bye_conversation", "chatterbot.corpus.chinese.squirral_normal_conversation", "chatterbot.corpus.chinese.squirral_rabbit_bye_conversation", "chatterbot.corpus.chinese.squirral_rabbit_conversation")

    def getResponse(self, message=""):
        return self.chatbot.get_response(message)

if __name__ == "__main__":
    bot = SquirralBot()
    print(bot.getResponse(sys.argv[1]))
```

**Comment by gunthercox** [comment] 2018-12-30 16:45
Hi, I'll try to answer all of your questions as soon as I can. At least for the first air that you encountered, the issue is likely related to capitalization. Use `ChatBot` instead of `Chatbot`.

**Comment by vkosuri** [comment] 2019-01-01 04:17
To avoid this confusion going forward ``ChatBot`` replace with ``chat_bot`` in feature release?

**Comment by gunthercox** [comment] 2019-01-02 01:52
@vkosuri I suppose that could possibly prevent confusion to an extent, but I'd prefer to follow the recommended naming conventions for classes in Python.

https://www.python.org/dev/peps/pep-0008/#class-names

**Comment by gunthercox** [comment] 2019-01-11 22:18
@herboratory Following up with your other questions.

2. ChatterBot will select a response from the corpus that contains the best matching response to the input it receives. So, if a user types "Bye" it will select a response accordingly based on the closest match that it can find, regardless of what set of training data, or corpus the response originated from.

3. There is noting built into ChatterBot that handles using multiple databases for a chat bot. However, there are ways to achieve functionality close to this. For example, you might be able to use multiple chat bots that each have there own database, such that each chat bot is a "specialist" in some subject matter.

4. ChatterBot just provides functions for generating responses. It doesn't have anything for delayed or timed responses built in. This is probably something that you would code into your program outside of ChatterBot.

**Comment by gunthercox** [comment] 2019-01-17 01:35
@herboratory I hope those explanations helped. I'm going to close this ticket off. Please let me know if you require further elaborations on the items I mentioned, or feel free to open a new issue if you have additional questions.

**Closed** 2019-01-17 02:04 UTC
Labels: answered

**Comment by DevakrishnanKV** [comment] 2019-07-11 13:38
I have some issues in chatbot after training.if user type Hi the chatbot gives different answer like what is basketball.it took different yml conversation for greetings..Not only for greetings all the questions it give answer unrelatively
