### ISSUE TITLE
Mongo DB error: distinct too big, 16mb cap

### ISSUE THREAD

**Issue by yunsonbai** [gunthercox/ChatterBot#452] opened 2016-12-02 07:11 UTC
```
error: 
        distinct too big, 16mb cap
mongodb data size: 
        hatterbot-database	0.953125GB
```

**Comment by cesarandreslopez** [comment] 2016-12-06 03:17
Same error here. Not with one of the examples though but with an import of https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html in particular the movie_lines.txt 

The import is fine and it will work upto some point while importing but by the time the import is done I will get a pymongo.errors.OperationFailure: distinct too big, 16mb cap error. I will try again limiting the length of the phrases to 160 characters and report back.

**Comment by cesarandreslopez** [comment] 2016-12-06 04:22
@gunthercox i can confirm that if the size of the of text or phrase is limited (tried 160 characters) i see no  "Mongo DB error: distinct too big, 16mb cap" error.

**Comment by gunthercox** [comment] 2016-12-10 01:49
I'm going to close this ticket off as it is a duplicate of #261

**Closed by gunthercox** 2016-12-10 01:49 UTC
Labels: bug
