### ISSUE TITLE
Changing default language of the math evaluation logic adapter

### ISSUE THREAD

**Issue by xiaolitang** [gunthercox/ChatterBot#1115] opened 2017-12-13 04:10 UTC
Hello!

I was wondering if it is possible to the change the default language 'ENG' into other languages of the mathematical evaluation logic adapter at this stage? 

Thank you very much!

**Comment by gunthercox** [comment] 2017-12-13 12:04
```
ChatBot(
    language='ITA'
)
```

I will note, that not all languages are supported by the mathematical evaluation adapter yet. You can find out the list of supported languages by looking at the `MATH_WORDS` dictionary in https://github.com/gunthercox/mathparse/blob/master/mathparse/mathwords.py

(MathParse is the library that ChatterBot uses to evaluate math string expressions)

**Comment by xiaolitang** [comment] 2017-12-14 00:45
Thank you gunthercox,

I added Mandarin into the dictionary in MathParse file and changed the default language. But when I ran the bot, it never went through the mathematical evaluation logic adapter.

The logging shows:
INFO:chatterbot.adapters:Not processing the statement using MathematicalEvaluation

This occurs no matter the order of logic adapters I put when initialising the bot.

**Comment by gunthercox** [comment] 2017-12-14 00:59
What was the input? Perhaps it was something that the math adapter didn't detect as a mathematical string?

**Comment by xiaolitang** [comment] 2017-12-14 07:59
Thank you gunthercox,

My input was '二加二‘ in Mandarin which means 'two plus two'. 
I have made some changes in math word file that indicating '二‘ and '加' represents 2 and + respectively, as other languages.

**Comment by gunthercox** [comment] 2017-12-14 12:47
Ah, I think I know what the issue is. The tokenizer in the mathparse library splits math tokens based on spaces. I think I'll have to make some adjustments to the code to change how it tokenizes Mandarin.

**Comment by xiaolitang** [comment] 2017-12-15 05:51
Thanks gunthercox,

I see. Thank you in advance for the adjustments to fit Mandarin.

**Comment by gunthercox** [comment] 2017-12-20 12:49
I'm going to close this ticket off, I've created a new one with a proposed solution in the issue tracker for mathparse (https://github.com/gunthercox/mathparse/issues/19).

@xiaolitang I might have a few more questions about Mandarin that I may need your help with.

**Closed by gunthercox** 2017-12-20 12:49 UTC
Labels: bug

**Comment by xiaolitang** [comment] 2017-12-20 13:31
Sure, I would love to help ;)
