### ISSUE TITLE
bot.get_response(input_msg) is very slow when used to get response from mongodb

### ISSUE THREAD

**Issue by jm33-m0** [gunthercox/ChatterBot#697] opened 2017-04-20 09:38 UTC
i have about 30k lines of training data, which has been imported into mongodb using `ListTrainer`, when i try to use `bot.get_response(input_msg)` to get response for a single input message, it uses 100% of one of my cpu cores, getting response takes more than 5 seconds (takes even longer on a low-end vps)

please give me some advice to speed up the chatbot, thanks

**Comment by vkosuri** [comment] 2017-04-20 11:07
@jm33-m0 What version of chatterbot and Mango db are you using?

I felt the problem is on Mongo DB, some of the useful links to resolve your issue

https://jira.mongodb.org/browse/SERVER-19485
https://dba.stackexchange.com/questions/137723/memory-usage-of-mongodb

And also try use [mongostat](https://docs.mongodb.com/manual/reference/program/mongostat/) to capture more results.

**Comment by jm33-m0** [comment] 2017-04-20 11:34
@vkosuri here is my mongodb version info:
```
MongoDB shell version: 3.2.11
connecting to: version
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
```
so it's not an issue with chatterbot? i see python taking 100% of a cpu core not mongodb (weird)

**Comment by jm33-m0** [comment] 2017-04-20 11:50
i enabled logging and found the problem:
it takes some time to select a response, and that's where cpu usage achieves 100% (single core)

i really don't know how to make mongodb faster as it's already running fine (at least working without errors)

**Comment by vkosuri** [comment] 2017-04-20 11:56
You could find where exactly your memory consuming by python, using concept [profile](https://docs.python.org/2/library/profile.html)

could you please try profile your script by redirect stats into external file e.g.: output_file.log, more info https://docs.python.org/2/library/profile.html#instant-user-s-manual

``` Bash
python -m cProfile -o output_file.log examples/terminal_example.py
```

**Comment by jm33-m0** [comment] 2017-04-20 12:09
@vkosuri `output_file.log` is a huge binary file (more than 2k lines when loaded by `xxd`) containing too much info...
im quite sure that chatterbot stucks at `bot.get_response(input_msg)`, where it selects response from mongodb

**Comment by jm33-m0** [comment] 2017-04-20 12:16
@vkosuri 
im using `terminal_mongo_example.py` as an example, the database is the same huge one
here is what my `output_file.log` says:
```
$ python3 readlog.py 
Thu Apr 20 20:04:53 2017    output_file.txt

         9876104 function calls (9824814 primitive calls) in 14.601 seconds

   Ordered by: cumulative time
   List reduced from 3819 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    888/1    0.044    0.000   14.633   14.633 {built-in method builtins.exec}
        1    0.000    0.000   14.633   14.633 mongo_chatter.py:2(<module>)
        2    0.000    0.000   13.789    6.894 /usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py:97(get_response)
        2    0.000    0.000    7.573    3.787 /usr/local/lib/python3.5/dist-packages/chatterbot/input/input_adapter.py:17(process_input_statement)
        2    0.000    0.000    7.572    3.786 /usr/local/lib/python3.5/dist-packages/chatterbot/input/terminal.py:13(process_input)
        2    0.000    0.000    7.572    3.786 /usr/local/lib/python3.5/dist-packages/chatterbot/utils.py:72(input_function)
        2    7.572    3.786    7.572    3.786 {built-in method builtins.input}
        1    0.000    0.000    6.215    6.215 /usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py:127(generate_response)
        1    0.000    0.000    6.215    6.215 /usr/local/lib/python3.5/dist-packages/chatterbot/logic/multi_adapter.py:25(process)
        1    0.016    0.016    6.214    6.214 /usr/local/lib/python3.5/dist-packages/chatterbot/logic/best_match.py:51(process)
```

**Comment by jm33-m0** [comment] 2017-04-20 13:18
and `mongostat` shows:
(took **half a minute** to generate a response)
> CPU is: `Model name:            Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz`
```
    *0      2     *0     *0       1     3|0       0    80m   429m    60m      0 chatterbot-database:0.0%          0       0|0     0|0   925b     4m     3   13:13:52 
    *0     *0     *0     *0       0     1|0       1    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:13:53 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:13:54 
insert  query update delete getmore command flushes mapped  vsize    res faults                locked db idx miss %     qr|qw   ar|aw  netIn netOut  conn       time 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:13:55 
    *0     *0     *0     *0       0     2|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0   120b     3k     3   13:13:56 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:13:57 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:13:58 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:13:59 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0                   .:0.0%          0       0|0     0|0    62b     3k     3   13:14:00 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:01 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:02 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:03 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:04 
insert  query update delete getmore command flushes mapped  vsize    res faults                locked db idx miss %     qr|qw   ar|aw  netIn netOut  conn       time 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:05 
    *0     *0     *0     *0       0     2|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0   120b     3k     3   13:14:06 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:07 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:08 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:09 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:10 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:11 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:13 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:14 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:15 
insert  query update delete getmore command flushes mapped  vsize    res faults                locked db idx miss %     qr|qw   ar|aw  netIn netOut  conn       time 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:16 
    *0     *0     *0     *0       0     2|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0   120b     3k     3   13:14:17 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:18 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:19 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:20 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:21 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:22 
    *0     *0     *0     *0       0     1|0       0    80m   429m    60m      0               local:0.0%          0       0|0     0|0    62b     3k     3   13:14:23 
    *0      1     *0     *0       0     1|0       0    80m   429m    60m      0 chatterbot-database:0.0%          0       0|0     0|0   644b    68k     3   13:14:24
```

**Comment by vkosuri** [comment] 2017-04-20 18:04
> 2 7.572 3.786 7.572 3.786 {built-in method builtins.input}

It related to Terminal Input https://docs.python.org/3/library/functions.html#input

I am also not sure where exactly your memory is consuming? 

Did you tried these methods to resolve your issues?
https://jira.mongodb.org/browse/SERVER-19485
https://dba.stackexchange.com/questions/137723/memory-usage-of-mongodb

**Comment by jm33-m0** [comment] 2017-04-21 01:34
memory is fine, it's consuming CPU, as `mongostat` shows, it stucks at selecting response, so I think it's a problem with chatter bot

**Comment by Madhu009** [comment] 2017-04-21 16:24
@jm33-m0 @vkosuri  I also encountered the same issue 

Here is what I observed 

--> Logic -->Bestmatch-->statement_list = self.chatbot.storage.get_response_statements() 

the above statement reads the entire data so it is taking much time 
this reads either from json file storage or mongod file storage.

The loop is running for O(datasize) which is why it is taking much time

this is just my understanding, so please let me know if there is a way to make the response fast.

**Comment by yeshoujquery** [comment] 2017-04-25 03:15
@jm33-m0  
I also have this problem I also choose to use mongodb3.x but the reaction speed of the robot is particularly slow I traced the code is found code processing problem has been in circulation rather than a similar kind of TF LSTM RNN and the mechanism of the robot but also want to give up trying to save the author do not know to have to modify your reaction speed too slow?

**Comment by jm33-m0** [comment] 2017-04-25 14:42
@yeshoujquery sorry, but i am not sure i understand your comment, could you please put some commas in it?
i am seeking some alternatives like DeepQA (based on tensorflow), but haven't tried any of them

**Comment by yeshoujquery** [comment] 2017-04-26 02:44
@jm33-m0 DeepQA I have tried, the training time a little longer, I mean, chatterbot can not carry a large amount of data, if you try to succeed can share the results?

**Comment by anilneeluri** [comment] 2017-08-10 13:25
@jm33-m0 What is the memory size of your dataset and  Whats the  format of the data?

**Comment by lesleslie** [comment] 2017-08-10 13:58
My data set is 8.9M and is all loaded from pickled lists generated by my CorpusTool, which is part of fBot (https://github.com/lesleslie/fBot - fBot lacks documentation but if you can install, run it, and  figure out what it does you'll realize that this is probably a good thing) but I will prob split it off because it is a standalone tool.  CorpusTool will scrape webpages for song lyrics, quotes, or movie scripts and generate pickled files of lists that can be loaded into the ListTrainer.  

See the file changes for pull request #916.  There are changes to mongodb.py that make it possible for me to use a dataset of this size which are not committed to the main branch (yet?).  Most notably changing distinct to aggregate and then increasing the size of the sort buffer.  Look at the file diffs.

With a dataset of this size, even with my changes, you should expect >2 mins for the query when using Levenstein distance.  If you only have 30k of data you should get almost an immediate response.  When trained with English corpora that comes with Chatterbot, and CorpusTrainer, I was getting really fast responses even with four logic adapters daisy-chained together - i.e.:

{
            'import_path': 'chatterbot.logic.BestMatch',  # Levenshtein distance by default
            'response_selection_method': 'chatterbot.response_selection.get_random_response',
        },
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'statement_comparison_function': 'chatterbot.comparisons.synset_distance',
            'response_selection_method': 'chatterbot.response_selection.get_random_response',
        },
        {
           'import_path': 'chatterbot.logic.BestMatch',
           'statement_comparison_function': 'chatterbot.comparisons.sentiment_comparison',
           'response_selection_method': 'chatterbot.response_selection.get_random_response',
         },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.24,
            'default_response': choice(st['low_responses']),
        }

(I don't use jaccard_similarity btw because even though it seems to be working sometimes it does generate a float error - at least on OSX).

Also, make sure you are using a version of ChatterBot >= 7.4.  If your training list is in bytes format too, i.e. b'my list string' your query performance will be much slower.  You shouldn't need to encode utf-8 to bytes if you are using Python 3.  (almost all of my recommendations are just from my experience or googling fyi).

-- les

**Comment by zxsimple** [comment] 2018-01-17 01:55
@jm33-m0 ，you probably hasn't install python-Levenshtein， please check whether [https://github.com/gunthercox/ChatterBot/pull/1158](https://github.com/gunthercox/ChatterBot/pull/1158) is helpful or not

**Closed** 2018-10-12 01:46 UTC
