### ISSUE TITLE
can't use the new logical adapters 

### ISSUE THREAD

**Issue by sumn2u** [gunthercox/ChatterBot#265] opened 2016-08-29 04:38 UTC
I am building own approximate sentence matching logic adapter which uses Jaccard index. I create it under /usr/local/lib/python3.5/dist-packages/chatterbot/adapters/logic/logic_Adapter.py. It shows me error like this.
```
   confidence, response = self.logic.process(input_statement)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/adapters/logic/multi_adapter.py", line 27, in process
    confidence, output = adapter.process(statement)
TypeError: 'NoneType' object is not iterable
```
My Source code is .
```
# Imports
import nltk.corpus
import nltk.tokenize.punkt
import nltk.stem.snowball
from nltk.corpus import wordnet
import string
from chatterbot.adapters import Adapter

class LogicAdapter(Adapter):
    """
    This is an abstract class that represents the interface
    that all logic adapters should implement.
    """

    def can_process(self, statement):
        """
        A preliminary check that is called to determine if a
        logic adapter can process a given statement. By default,
        this method returns true but it can be overridden in
        child classes as needed.
        """
        return True

    def process(self, statement):
        # """
        # Method that takes an input statement and returns
        # a confidence value and a statement as output.
        # """

        # raise self.AdapterMethodNotImplementedError()
        # Get default English stopwords and extend with punctuation
        stopwords = nltk.corpus.stopwords.words('english')
        stopwords.extend(string.punctuation)
        stopwords.append('')

        def get_wordnet_pos(pos_tag):
            if pos_tag[1].startswith('J'):
                return (pos_tag[0], wordnet.ADJ)
            elif pos_tag[1].startswith('V'):
                return (pos_tag[0], wordnet.VERB)
            elif pos_tag[1].startswith('N'):
                return (pos_tag[0], wordnet.NOUN)
            elif pos_tag[1].startswith('R'):
                return (pos_tag[0], wordnet.ADV)
            else:
                return (pos_tag[0], wordnet.NOUN)

        # Create tokenizer and stemmer
        # tokenizer = nltk.tokenize.word_tokenize()
        lemmatizer = nltk.stem.wordnet.WordNetLemmatizer()

        def is_ci_lemma_stopword_set_match(a, b, threshold=0.5):
            """Check if a and b are matches."""
            pos_a = map(get_wordnet_pos, nltk.pos_tag(tokenizer.nltk.tokenize.word_tokenize(a)))
            pos_b = map(get_wordnet_pos, nltk.pos_tag(tokenizer.nltk.tokenize.word_tokenize(b)))
            lemmae_a = [lemmatizer.lemmatize(token.lower().strip(string.punctuation), pos) for token, pos in pos_a \
                            if pos == wordnet.NOUN and token.lower().strip(string.punctuation) not in stopwords]
            lemmae_b = [lemmatizer.lemmatize(token.lower().strip(string.punctuation), pos) for token, pos in pos_b \
                            if pos == wordnet.NOUN and token.lower().strip(string.punctuation) not in stopwords]

            # Calculate Jaccard similarity
            ratio = len(set(lemmae_a).intersection(lemmae_b)) / float(len(set(lemmae_a).union(lemmae_b)))
            return (ratio >= threshold)
        def get(self, input_statement):
            """
            Takes a statement string and a list of statement strings.
            Returns the approximate matching statement from the list.
            """
            statement_list = self.context.storage.get_response_statements()
            print(statement_list)
            if not statement_list:
                if self.has_storage_context:
                    # Use a randomly picked statement
                    self.logger.info(
                        u'No statements have known responses. ' +
                        u'Choosing a random response to return.'
                        )
                    return 0, self.context.storage.get_random()
                else:
                    raise self.EmptyDatasetException()

            confidence = -1
            closest_match = input_statement
            # Find the closest matching known statement
            for statement in statement_list:
                print("statement", statement.text);
                # ratio = fuzz.ratio(input_statement.text, statement.text)
                ratio = is_ci_lemma_stopword_set_match(input_statement.text, statement.text)
                if ratio > confidence:
                    confidence = ratio
                    closest_match = statement
                    # Convert the confidence integer to a percent
                confidence /= 100.0
                return confidence, closest_match

    class EmptyDatasetException(Exception):

        def __init__(self, value="An empty set was received when at least one statement was expected."):
            self.value = value

        def __str__(self):
            return repr(self.value)

```

**Comment by gunthercox** [comment] 2016-08-29 16:44
Hi @sumn2u, there are a few issues I can see right off the bat. I think I can help you solve the issue you are encountering.

***

First, it appears that your logic adapter is inheriting from the `Adapter` class when it should be inheriting from the `LogicAdapter class. To fix this, you can just change your imports from:

```python
from chatterbot.adapters import Adapter
...
class LogicAdapter(Adapter):
```
to:
```python
from chatterbot.adapters.logic import LogicAdapter

class LogicAdapter(LogicAdapter):
```
(Another example of the imports can be seen in the [documentation](http://chatterbot.readthedocs.io/en/latest/adapters/logic.html#creating-a-new-logic-adapter) on logic adapters.)

***

You can remove the `can_process` from your adapter if you don't pan to implement any logic for it. This method returns true by default and now that we are inheriting from `LogicAdapter` the method will be inherited from the parent class. 

For the same reason as described above, you can also remove the `EmptyDatasetException` subclass from your new logic adapter unless you specifically plan to override it.

***

The other thing I noticed is that there is an edge case that may cause problems when you are iterating over your statement list. I believe the return statement needs to be tabbed back one indentation level. As it is currently written, it will return the first `confidence` and `closest_match` value that it comes across on the first iteration of the for loop. Another issue caused by this is that if `statement_list` is empty, **nothing** will be returned from this method because the return statement is never hit (I believe this is the cause of the exception you were getting).

So change:
```python
            for statement in statement_list:
                ...
                return confidence, closest_match
```
to:
```python
            for statement in statement_list:
                ...
            return confidence, closest_match
```

***

Those are the only immediate issues I can see. I did not get a chance to test the piece of code you submitted but I believe you should be in a better place now. Bellow you will find a the full snippet with all the changes I've suggested already made.

```python
# Imports
import nltk.corpus
import nltk.tokenize.punkt
import nltk.stem.snowball
from nltk.corpus import wordnet
import string
from chatterbot.adapters.logic import LogicAdapter

class LogicAdapter(LogicAdapter):
    """
    This is an abstract class that represents the interface
    that all logic adapters should implement.
    """

    def process(self, statement):
        # Get default English stopwords and extend with punctuation
        stopwords = nltk.corpus.stopwords.words('english')
        stopwords.extend(string.punctuation)
        stopwords.append('')

        def get_wordnet_pos(pos_tag):
            if pos_tag[1].startswith('J'):
                return (pos_tag[0], wordnet.ADJ)
            elif pos_tag[1].startswith('V'):
                return (pos_tag[0], wordnet.VERB)
            elif pos_tag[1].startswith('N'):
                return (pos_tag[0], wordnet.NOUN)
            elif pos_tag[1].startswith('R'):
                return (pos_tag[0], wordnet.ADV)
            else:
                return (pos_tag[0], wordnet.NOUN)

        # Create tokenizer and stemmer
        # tokenizer = nltk.tokenize.word_tokenize()
        lemmatizer = nltk.stem.wordnet.WordNetLemmatizer()

        def is_ci_lemma_stopword_set_match(a, b, threshold=0.5):
            """Check if a and b are matches."""
            pos_a = map(get_wordnet_pos, nltk.pos_tag(tokenizer.nltk.tokenize.word_tokenize(a)))
            pos_b = map(get_wordnet_pos, nltk.pos_tag(tokenizer.nltk.tokenize.word_tokenize(b)))
            lemmae_a = [lemmatizer.lemmatize(token.lower().strip(string.punctuation), pos) for token, pos in pos_a \
                            if pos == wordnet.NOUN and token.lower().strip(string.punctuation) not in stopwords]
            lemmae_b = [lemmatizer.lemmatize(token.lower().strip(string.punctuation), pos) for token, pos in pos_b \
                            if pos == wordnet.NOUN and token.lower().strip(string.punctuation) not in stopwords]

            # Calculate Jaccard similarity
            ratio = len(set(lemmae_a).intersection(lemmae_b)) / float(len(set(lemmae_a).union(lemmae_b)))
            return (ratio >= threshold)

        def get(self, input_statement):
            """
            Takes a statement string and a list of statement strings.
            Returns the approximate matching statement from the list.
            """
            statement_list = self.context.storage.get_response_statements()
            print(statement_list)
            if not statement_list:
                if self.has_storage_context:
                    # Use a randomly picked statement
                    self.logger.info(
                        u'No statements have known responses. ' +
                        u'Choosing a random response to return.'
                        )
                    return 0, self.context.storage.get_random()
                else:
                    raise self.EmptyDatasetException()

            confidence = -1
            closest_match = input_statement
            # Find the closest matching known statement
            for statement in statement_list:
                print("statement", statement.text);
                # ratio = fuzz.ratio(input_statement.text, statement.text)
                ratio = is_ci_lemma_stopword_set_match(input_statement.text, statement.text)
                if ratio > confidence:
                    confidence = ratio
                    closest_match = statement
                    # Convert the confidence integer to a percent
                confidence /= 100.0
            return confidence, closest_match
```

**Comment by sumn2u** [comment] 2016-08-29 16:56
Thank you @gunthercox  well i have workout much and change something 
```
# -*- coding: utf-8 -*-
from .base_match import BaseMatchAdapter
from fuzzywuzzy import fuzz
import nltk.corpus
import nltk.tokenize.punkt
import nltk.stem.snowball
from nltk.corpus import wordnet
import string
class ApproximateSentenceMatchAdapter(BaseMatchAdapter):
    """
    The Jaccard index is composed of a numerator and denominator.
    In the numerator, we count the number of items that are shared between the sets.
    In the denominator, we count the total number of items across both sets.
    In our example  our intersection is {cat, hungry}, which has count of two.
    The union of the sets is {young, cat, very, hungry}, which has a count of four.
    Therefore, our Jaccard similarity index is two divided by four, or 50%.
    Given our threshold above, we would consider this to be  a match
    """
    def __init__(self, **kwargs):
        super(ClosestMatchAdapter, self).__init__(**kwargs)
        # self.is_ci_lemma_stopword_set_match()
        # self.get_wordnet_pos()
        # Get default English stopwords and extend with punctuation
        self.stopwords = nltk.corpus.stopwords.words('english')
        self.stopwords.extend(string.punctuation)
        self.stopwords.append('')
        self.lemmatizer = nltk.stem.wordnet.WordNetLemmatizer()

    def get_wordnet_pos(self, pos_tag):
        if pos_tag[1].startswith('J'):
            return (pos_tag[0], wordnet.ADJ)
        elif pos_tag[1].startswith('V'):
            return (pos_tag[0], wordnet.VERB)
        elif pos_tag[1].startswith('N'):
            return (pos_tag[0], wordnet.NOUN)
        elif pos_tag[1].startswith('R'):
            return (pos_tag[0], wordnet.ADV)
        else:
            return (pos_tag[0], wordnet.NOUN)

    def is_ci_lemma_stopword_set_match(self,a, b, threshold=0.5):
        """Check if a and b are matches."""
        print("ask",a)
        ratio = 0
        pos_a = map(self.get_wordnet_pos, nltk.pos_tag(nltk.tokenize.word_tokenize(a)))
        pos_b = map(self.get_wordnet_pos, nltk.pos_tag(nltk.tokenize.word_tokenize(b)))
        lemmae_a = [self.lemmatizer.lemmatize(token.lower().strip(string.punctuation), pos) for token, pos in pos_a \
                        if pos == wordnet.NOUN and token.lower().strip(string.punctuation) not in self.stopwords]
        lemmae_b = [self.lemmatizer.lemmatize(token.lower().strip(string.punctuation), pos) for token, pos in pos_b \
                        if pos == wordnet.NOUN and token.lower().strip(string.punctuation) not in self.stopwords]

        # Calculate Jaccard similarity
        try:
            ratio = len(set(lemmae_a).intersection(lemmae_b)) / float(len(set(lemmae_a).union(lemmae_b)))
        except Exception as e:
            print("Error", e)
        return (ratio >= threshold)

    def get(self, input_statement):
        """
        Takes a statement string and a list of statement strings.
        Returns the closest matching statement from the list.
        """
        statement_list = self.context.storage.get_response_statements()

        if not statement_list:
            if self.has_storage_context:
                # Use a randomly picked statement
                return 0, self.context.storage.get_random()
            else:
                raise self.EmptyDatasetException()

        confidence = -1
        closest_match = input_statement

        # Find the closest matching known statement
        for statement in statement_list:
            ratio = self.is_ci_lemma_stopword_set_match(input_statement.text, statement.text)
            if ratio:
                confidence =87
                closest_match = statement
        '''
        closest_match, confidence = process.extractOne(
            input_statement.text,
            text_of_all_statements
        )
        '''

        # Convert the confidence integer to a percent
        confidence /= 100.0
        if closest_match == input_statement:
            closest_match.text = "We couldn't find that answer in our knowledge base.Try other"
        return confidence, closest_match

```
I can't use the closest match adapter because if the sentence contains **How are you doing ?**  and **How you doing ?** It returns same result so i used this one .

**Comment by gunthercox** [comment] 2016-09-02 17:15
@sumn2u Has the issue you encountered been fixed? Let me know if there is anything else I can clarify or help with.

**Comment by sumn2u** [comment] 2016-09-03 07:20
well i implement the jaccard index logic , i found it to have better performance . I have made a pull request  you can have a look [https://github.com/gunthercox/ChatterBot/pull/272](url) @gunthercox  please check this pull request .

**Closed** 2016-09-03 14:32 UTC
