### ISSUE TITLE
Feedback example

### ISSUE THREAD

**Issue by nalancer08** [gunthercox/ChatterBot#920] opened 2017-08-10 03:43 UTC
I trying to run example for feedback, with this code:

``` Python
bot = ChatBot(
    'test',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch'
    ],
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    database="../database.db",
)
DEFAULT_SESSION_ID = bot.default_session.id
def get_feedback():
    from chatterbot.utils import input_function
    text = input_function()

    if 'yes' in text.lower():
        return True
    elif 'no' in text.lower():
        return False
    else:
        print('Please type either "Yes" or "No"')
        return get_feedback()
print('Type something to begin...')
while True:
    try:
        input_statement = bot.input.process_input_statement()
        statement, response = bot.generate_response(input_statement, DEFAULT_SESSION_ID)
        print('\n Is "{}" this a coherent response to "{}"? \n'.format(response, input_statement))
        if get_feedback():
            bot.learn_response(response, input_statement)
        bot.output.process_response(response)
        bot.storage.add_to_converation(bot.default_session, statement, response)
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

And I got this error:

```Bash
Type something to begin...
hola

 Is "hola" this a coherent response to "hola"? 

yes
hola
Traceback (most recent call last):
  File "feedback.py", line 61, in <module>
    bot.storage.add_to_converation(bot.default_session, statement, response)
**AttributeError: 'SQLStorageAdapter' object has no attribute 'add_to_converation'`**
```

**Comment by vkosuri** [comment] 2017-08-10 07:00
@nalancer08 I think the example are working fine, which version of chatterbot are you using? To know current version of chatterbot, please paste below commands on your terminal.

``` Bash
python -m chatterbot --version
```

**Comment by nalancer08** [comment] 2017-08-10 12:54
Hi, I have 0.7.6

**Comment by lesleslie** [comment] 2017-08-10 12:59
Check your code.  converation has prob been corrected to conversation.
You're also going to run into an issue with the default_session.id cause it
has changed too.  See pull request #916.

Cheers,

-- les

**Comment by nalancer08** [comment] 2017-08-10 13:10
Hello @lesleslie how can I updated the code? Is there an a command?

**Comment by lesleslie** [comment] 2017-08-10 13:17
If your getting that error the problem is in your code not chatterbot.  The
spelling correction of conversation took place 6 hours ago.  Follow the
traceback from the error code you're getting and it will point you to which
module and which line is calling the wrong function.

-- les

**Comment by lesleslie** [comment] 2017-08-10 13:18
In your case line 61 in feedback.py needs converation changed to
conversation.

**Comment by lesleslie** [comment] 2017-08-10 13:21
Don't forget too to change default_session.id to default_conversation_id
too in your code.

**Comment by nalancer08** [comment] 2017-08-10 13:28
@lesleslie yes, I was reading the last corrections, this is my code with the corrections

```Python
from chatterbot import ChatBot

bot = ChatBot(
    'Feedback Learning Bot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch'
    ],
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    database="../database.db",

)

DEFAULT_SESSION_ID = bot.default_conversation_id

def get_feedback():
    from chatterbot.utils import input_function

    text = input_function()

    if 'yes' in text.lower():
        return True
    elif 'no' in text.lower():
        return False
    else:
        print('Please type either "Yes" or "No"')
        return get_feedback()


print('Type something to begin...')

while True:
    try:
        input_statement = bot.input.process_input_statement()
        statement, response = bot.generate_response(input_statement, DEFAULT_SESSION_ID)

        print('\n Is "{}" this a coherent response to "{}"? \n'.format(response, input_statement))

        if get_feedback():
            bot.learn_response(response, input_statement)

        bot.output.process_response(response)
        bot.storage.add_to_conversation(bot.default_session, statement, response)

    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

But now, I getting this error:

```
Traceback (most recent call last):
  File "feedback.py", line 15, in <module>
    DEFAULT_SESSION_ID = bot.default_conversation_id
AttributeError: 'ChatBot' object has no attribute 'default_conversation_id'
```

**Comment by nalancer08** [comment] 2017-08-10 13:48
@lesleslie I was checking the SQLAdapter code, but the function `add_to_conversation` doesn't exists, only `add_to_converation`

In the file sql_storage.py, line 248, ` def add_to_converation(self, conversation_id, statement, response):`

But in any case, return error

**Comment by nalancer08** [comment] 2017-08-10 13:53
@lesleslie 
I was cheking your fork, and you updated the code and adapters, to use the correct function `add_to_converation`, how can I upgrade the ChatterBot code to use correctly the examples?

**Comment by lesleslie** [comment] 2017-08-10 14:20
Ok, change back to default_session.id and try that.  We may be using
slightly different versions.

**Comment by nalancer08** [comment] 2017-08-10 14:52
@lesleslie I did it, but give me this error

```
Type something to begin...
hola

 Is "hola" this a coherent response to "hola"? 

yes
hola
Traceback (most recent call last):
  File "feedback.py", line 42, in <module>
    bot.storage.add_to_conversation(bot.default_session, statement, response)
AttributeError: 'SQLStorageAdapter' object has no attribute 'add_to_conversation'
m-C02SH023G8WP:bot2 eec000i$ 

 ```

**Comment by lesleslie** [comment] 2017-08-11 01:28
Look at chatterbot/storage/sql_storage.py and see what the name of the
function is in your version and adjust accordingly.

-- les

**Comment by nalancer08** [comment] 2017-08-11 16:59
Hi again @lesleslie 

I tested you fork repo, and installed, but the same example, now gave me this error

```
Type something to begin...
hi

 Is "hi" this a coherent response to "hi"? 

no
hi
Traceback (most recent call last):
  File "so.py", line 47, in <module>
    bot.storage.add_to_conversation(bot.default_session, statement, response)
  File "build/bdist.macosx-10.12-intel/egg/chatterbot/storage/sql_storage.py", line 266, in add_to_conversation
  File "build/bdist.macosx-10.12-intel/egg/sqlalchemy/orm/query.py", line 864, in get
  File "build/bdist.macosx-10.12-intel/egg/sqlalchemy/orm/query.py", line 875, in _get_impl
TypeError: object of type 'NoneType' has no len()

```

**Comment by lesleslie** [comment] 2017-08-11 17:09
My repo was constantly being tweaked and worked on recently so I'm not sure
when you downloaded it.  As of just a few hours ago is it passing all of
the tests and is stable.  Please try forking my version again and if you
run into the same problem again I'll give it a good look and help resolve
the issue.  My repo, as at stands as of RIGHT NOW is, I believe, about to
be merged into the main branch.

-- les

**Comment by lesleslie** [comment] 2017-08-11 17:15
Nevermind that last statement.  You need to change default_session to
conversation_id in line 61 of so.py.  Again if you follow the traceback, to
the Exception, it will tell you exactly where the error is occurring in the
code.  It may do you some good to read a python debugging tutorial.

-- les

**Comment by lesleslie** [comment] 2017-08-11 17:18
Make that line 47 in so.py.  I think I got it right this time.

-- les

**Comment by lesleslie** [comment] 2017-08-11 17:18
Sorry again, that's line 41 in so.py.  I'm doing this from my phone.

-- les

On Aug 11, 2017 10:15 AM, "les" <les@wedgwoodwebworks.com> wrote:

Nevermind that last statement.  You need to change default_session to
conversation_id in line 61 of so.py.  Again if you follow the traceback, to
the Exception, it will tell you exactly where the error is occurring in the
code.  It may do you some good to read a python debugging tutorial.

-- les

**Comment by lesleslie** [comment] 2017-08-13 07:14
@nalancer08 sorry but there is an issue with the sql_storage adapter right now.  the default_conversation_id can not be 'None' with sql databases.  i've been strictly using mongodb so i didn't see it and somehow all the tests pass this way.  i was just playing around with the sql_adapter again and see what you are talking about. good catch.  i have solution that i'll be proposing and pushing hopefully within the next hour or so.  stay tuned .....   i'll keep you informed.

i am referring to this:

TypeError: object of type 'NoneType' has no len()

as I got it too.

**Comment by lesleslie** [comment] 2017-08-13 07:41
this is my the workaround that i propose for you:

change DEFAULT_CONVERSATION_ID or DEFAULT_SESSION_ID or whatever you have in your code to bot.storage.create_conversation().  ie:

DEFAULT_CONVERSATION_ID = bot.storage.create_conversation()

this change makes more sense to me because each time you access the bot via terminal, or however you're doing it, it actually is it's own conversation and should be treated as such.  Let's say you talk to your bot in terminal mode and the somebody else then talks your bot in terminal mode - these are two separate conversations and should be treated as such.

what i am going to recommend in my pull request is changing DEFAULT_CONVERSATION_ID to just CONVERSATION_ID in examples/learning_feedback_example.py and examples/learning_new_response.py like so:

CONVERSATION_ID = bot.storage.create_conversation()

this would mean the rest of your code would need to change DEFAULT_CONVERSATION_ID to CONVERSATION_ID.

i will also be adding a line to learning new_response.py so lines 45-50 will now look like this:

        if get_feedback():
            print("please input the correct one")
            response1 = bot.input.process_input_statement()
            bot.learn_response(response1, input_statement)
            bot.storage.add_to_conversation(CONVERSATION_ID, statement, response1)
            print("Responses added to bot!")

this way the new response will be saved to the conversation too.

-- les

**Comment by lesleslie** [comment] 2017-08-13 08:18
@nalancer08 

see #927

**Comment by nalancer08** [comment] 2017-08-13 08:39
@lesleslie let me check

**Comment by gunthercox** [comment] 2018-10-07 12:18
I'm going to close this ticket off. ChatterBot has evolved quite a bit since this was opened and conversation/session IDs are no longer used. (Conversation has been simplified to just be a string attribute on each statement object).

**Closed by gunthercox** 2018-10-07 12:18 UTC
