### ISSUE TITLE
chatterbot library in python

### ISSUE THREAD

**Issue by Ishank8** [gunthercox/ChatterBot#1942] opened 2020-04-10 14:19 UTC
I have succesfully install chatterbot library in Python, but while running a program I got an error

 [nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HTC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 108, in nltk_download_corpus
    find(resource_path)
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 673, in find
    return find(modified_name, paths)
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 660, in find
    return ZipFilePathPointer(p, zipentry)
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\compat.py", line 228, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 506, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\compat.py", line 228, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 1055, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    chatbot=ChatBot('Ben')
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 58, in __init__
    self.initialize()
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 80, in initialize
    function()
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 197, in download_nltk_wordnet
    nltk_download_corpus('corpora/wordnet')
  File "C:\Users\HTC\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 114, in nltk_download_corpus
    'The NLTK corpus file being opened is not a zipfile, '
zipfile.BadZipFile: The NLTK corpus file being opened is not a zipfile, or it has been corrupted and needs to be manually deleted.
>>> 

Please help me

**Comment by gunthercox** [comment] 2020-08-29 19:38
The error message `zipfile.BadZipFile: File is not a zip file` usually indicates that one of the corpus files failed to download correctly. This can be fixed if you delete the existing ones and re-download them (they should be in a folder somewhere on your system called `nltk_data`.

**Comment by gunthercox** [comment] 2020-08-29 19:39
Duplicate of #1754

**Closed** 2020-09-13 20:27 UTC
Labels: answered
